# Generated by Django 2.2.3 on 2019-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0003_auto_20190708_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.BooleanField(default=True, verbose_name='Complete'),
        ),
    ]
