# Generated by Django 2.2.3 on 2019-07-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0004_auto_20190708_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='treatment',
        ),
    ]
