# Generated by Django 2.2.3 on 2019-07-09 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0005_remove_prescription_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
