# Generated by Django 2.2.3 on 2019-07-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0006_prescription_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
    ]
