# Generated by Django 2.2.3 on 2019-07-09 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0009_remove_prescription_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='guide',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
