# Generated by Django 2.2.3 on 2019-07-10 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0011_remove_prescription_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
